import { I18nManager, StyleSheet } from 'react-native';
import { BlueCurrentTheme } from './themes';

export const defaultStyles = StyleSheet.create({
  h1: {
    writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr',
    color: BlueCurrentTheme.colors.foreground,
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 40,
    textAlign: 'center',
  },
  h2: {
    writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr',
    color: BlueCurrentTheme.colors.foreground,
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 24,
  },
  h3: {
    writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr',
    color: BlueCurrentTheme.colors.foreground,
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 20,
  },
  h4: {
    writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr',
    color: BlueCurrentTheme.colors.foreground,
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 16,
  },
  label: {
    writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr',
    color: BlueCurrentTheme.colors.foregroundInactive,
    fontFamily: 'Poppins',
    fontWeight: '400',
    fontSize: 12,
  },
  hairline: {
    writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr',
    color: BlueCurrentTheme.colors.foregroundInactive,
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 12,
  },
  bodyText: {
    writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr',
    color: BlueCurrentTheme.colors.foregroundInactive,
    fontFamily: 'Poppins',
    fontWeight: '400',
    fontSize: 14,
  },
  inputText: {
    color: BlueCurrentTheme.colors.foreground,
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 14,
  },
  divider: { borderWidth: 0.5, borderColor: BlueCurrentTheme.colors.background },
  modal: {
    display: 'flex',
    flex: 1,
    justifyContent: 'space-between',
    marginTop: 60,
    padding: 24,
    borderRadius: 32,
    backgroundColor: BlueCurrentTheme.colors.element,
  },
  btn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 40,
    backgroundColor: BlueCurrentTheme.colors.button,
  },
  btnText: {
    color: BlueCurrentTheme.colors.white,
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 16,
  },
  btnSecondary: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
    borderRadius: 40,
    backgroundColor: BlueCurrentTheme.colors.dark,
  },
  btnSecondaryText: {
    color: BlueCurrentTheme.colors.button,
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 16,
  },
});
